version: '3.6'
services:
  vuejs:
    image: node:12
    volumes:
      - ./project:/project
      - ./vuejs.sh:/vuejs.sh
    ports:
      - 8111:8080
      - 8112:8000
    entrypoint: ["/vuejs.sh"]
    working_dir: /project

  api:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.7
    volumes:
      - ./project/api:/app
    ports:
      - 8113:80
    entrypoint: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80", "--workers","2","--reload"]
